#
name: immich-mlrm
services:
  immich-machine-learning:
    container_name: immich_machine_learning_remote
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5-cuda
    ports:
      - "3003:3003" # Öffnet den Port für das NAS
    volumes:
      - ./model-cache:/cache # Speichert die heruntergeladenen KI-Modelle lokal
    environment:
      - TZ=Europe/Vienna
    # Aktivierung der GTX 1070ti
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video, compute, utility]
    restart: unless-stopped
