# ~/.config/fuzzel/fuzzel.ini

[main]
# Die zentrale Kausalität: Jede gestartete App wird eine eigene uWSM-Unit
launcher-prefix=uwsm app --
icon-theme=Papirus-Dark
font=sans-serif:size=10
terminal=kitty
prompt=" "
layer=overlay
# Positioniert Fuzzel mittig für den Fokus deines i7-7700K
anchor=center

include=~/.config/hypr/assets/fuzzel-colors

[border]
width=2
radius=10
