# ~/.config/fuzzel/fuzzel.ini

[main]
# Die zentrale Kausalität: Jede gestartete App wird eine eigene uWSM-Unit
launcher-prefix=uwsm app --
icon-theme=Papirus-Dark
font=sans-serif:size=10
terminal=kitty
prompt="❯  "
layer=overlay
# Positioniert Fuzzel mittig für den Fokus deines i7-7700K
anchor=center

[colors]
# Passend zu deinem grauen Adwaita/Mako Design
# Format: RRGGBBAA
background=1e1e1ed5
text=dcdcdcff
match=62cdffff
selection=444444ff
selection-text=62cdffff
border=444444ff

[border]
width=2
radius=10
