##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


####################
### WINDOW RULES ###
####################

#workspace = special:magic, size 30% 100%, move 70% 0%
#workspace = special:monitor, size 30% 100%, move 70% 0%
windowrule = match:fullscreen 1, border_size 0
windowrule = match:class org.pulseaudio.pavucontrol, float 1, move (cursor_x-(window_w*1)) (cursor_y-(window_h*0))
#windowrule = match:class $BROWSER_CLASS
windowrule = match:class Horizon-client, workspace 3
windowrule = match:title VDI.*, fullscreen 1
windowrule = match:class steam, workspace special:magic, pseudo 1, size 1266 706
windowrule = match:class vesktop, float 1, opaque 1 # discord
windowrule = match:class bolt-launcher, workspace special:magic, pseudo 1, # discord
windowrule = match:class chrome-web.webex.com.*, workspace special:magic, pseudo 1,  opaque 1 # webex-web-app
windowrule = match:class cs2, workspace empty
windowrule = match:class net-runelite-client-RuneLite, workspace empty, opaque 1
windowrule = match:class steam_app_1343400, workspace 5, opaque 1
windowrule = match:class htop-sys, workspace special:monitor, pseudo 1,  opacity 0.95
windowrule = match:class nvtop-sys, workspace special:monitor, pseudo 1,  opacity 0.95
