wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/assets/wallpapers/Forest1.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/assets/wallpapers/Forest1.png
    fit_mode = cover
}
