##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


####################
### WINDOW RULES ###
####################

windowrule = match:workspace 1, monitor DP-2
windowrule = match:workspace 2, monitor DP-3
windowrule = match:workspace 3, monitor DP-2
windowrule = match:workspace 4, monitor DP-3
windowrule = match:fullscreen 1, border_size 0
windowrule = match:class $BROWSER_CLASS, monitor DP-3
windowrule = match:class Horizon-client, workspace 3, monitor DP-2, float 1, fullscreen 1
windowrule = match:class CiscoCollabHost, workspace 4, monitor DP-3, float 0 
