###################################################################
### Sets Variables and Autostart for Hyprland (hyprland.conf)
###################################################################

### ENV are manages by UWSM ###

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

### Standard programs set via ENVS in UWSM ###

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# Use "uwsm --app" to ensure clean starts in isolated sessions

exec-once = uwsm app -- $PANEL
#exec-once = uwsm app -- $WPM # Managed by Daemon
exec-once = uwsm app -- $IDLEM
exec-once = uwsm app -- $POLKIT
exec-once = uwsm app -- $NOTD
exec-once = uwsm app -- $BROWSER
exec-once = $HOME/.local/bin/hypr-lazy.sh # lazy loads plugins on trigger, eg. system-monitor

