###################################################################
### Sets Variables and Autostart for Hyprland (hyprland.conf)
###################################################################

### ENV are manages by UWSM ###

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

### Standard programs set via ENVS in UWSM ###

#################
### AUTOSTART ###
#################

# Autostart - deamons (waybar, hyprpaper, etc.) are managed by systemd!
# Or execute your favorite apps at launch like this:
# Use "uwsm --app" to ensure clean starts in isolated sessions
exec-once = uwsm app -- valent --gapplication-service
exec-once = uwsm app -- $BROWSER
