---
- name: Ensure configuration directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
  loop:
    - { path: /opt/containerd/semaphore/db }
    - { path: /opt/containerd/semaphore/playbooks }
    - { path: /opt/containerd/prometheus/config }
    - { path: /opt/containerd/prometheus/data, owner: '65534' } # prometheus (nobody)
    - { path: /opt/containerd/grafana/data, owner: '472' }       # grafana

- name: Deploy Prometheus configuration
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/containerd/prometheus/config/prometheus.yml
    mode: '0644'

- name: Deploy Docker Compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/containerd/admin_stack/docker-compose.yml
    mode: '0644'

- name: Start Monitoring Stack (Docker Compose)
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/containerd/admin_stack/
    state: present
    wait: true
