--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiIgnoreDriverChecks,Default
--disable-features=UseChromeOSDirectVideoDecoder,Vulkan
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--use-gl=angle
--ozone-platform-hint=auto
