 # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors

$borderactive1 = rgba($BORDERACTIVE0) #dark blue
$borderactive2 = rgba($BORDERACTIVE1) #light blue, vibrant
$borderinactive = rgba($BORDERINACTIVE) #grey, translucent
