 # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors

$borderactive1 = rgba(0071a6ff) #dark blue
$borderactive2 = rgba(62cdffff) #light blue, vibrant
$borderinactive = rgba(595959aa) #grey, translucent
